name: Build and Publish
on:
  push:
    branches:
      - master
      - BAH-1415
    paths-ignore:
      - "**.md"
  repository_dispatch:
    types: ["bahmni-package-trigger"]
  workflow_dispatch:
env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Checkout OpenERP Atomfeed Service Repo
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
      - name: Package
        run: mvn --no-transfer-progress clean package -DskipTests
      - name: Copy package to docker resource
        run: cp openerp-atomfeed-service/target/openerp-atomfeed-service.war package/resources
      - name: Checkout bahmni-package to use embedded tomcat project
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-package
          path: ../bahmni-package
      - name: Build Docker Image
        run: ./package/docker/scripts/docker_build.sh
      - name: List Docker Images
        run: docker images
      - name: Push Docker Images
        run: ./package/docker/scripts/docker_publish.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
