name: Continuous Integration-v0.94
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-package:
    name: Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Checkout OpenERP Atomfeed Service Repo
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
      - name: Package
        run: mvn --no-transfer-progress clean package -DskipTests
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: openerp-atomfeed-war
          path: openerp-atomfeed-service/target/openerp-atomfeed-service.war
  docker-build-publish:
    name: Build & Publish Docker Image
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Checkout bahmni-package
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-package
          ref: odoo-connect-docker
      - uses: actions/download-artifact@v2
        with:
          name: openerp-atomfeed-war
          path: bahmni-erp-connect/resources
