name: Continuous Integration-v0.94
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-package:
    name: Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Checkout OpenERP Atomfeed Service Repo
        uses: actions/checkout@v2
        with:
          path: openerp-atomfeed-service
      - name: Run Unit Tests
        run: mvn --no-transfer-progress clean test
